export { ReactComponent as SearchIcon24 } from './search24.svg'
export { ReactComponent as SearchIcon48 } from './search48.svg'
export { ReactComponent as Favorite1 } from './bookmark1.svg'
export { ReactComponent as Favorite2 } from './bookmark2.svg'
export { ReactComponent as Favorite3 } from './bookmark3.svg'
